spring.jpa.properties.hibernate.dialect:org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

security.token.secret=GESTAO_VAGAS768##
security.token.secret.candidate=GESTAO_VAGAS768##CANDIDATE

management.endpoints.access.default=none
management.endpoints.web.exposure.include=health, metrics, prometheus
management.endpoint.health.access=unrestricted
management.endpoint.health.show-details=always
management.endpoint.metrics.access=read-only
management.endpoint.prometheus.access=read-only